# Generated by Django 5.0.4 on 2026-08-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=30, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_DISPATCH', 'On Dispatch'), ('MAINTENANCE', 'In Maintenance')], default='AVAILABLE', max_length=20)),
                ('current_location', models.CharField(default='Hospital Station', max_length=200)),
            ],
        ),
    ]
